# RandomGift configuration

# Items that are chosen at random
#  - 'ID[:data value] Quantity'
items:
  - '267 1'
  - '256 1'
  - '257 1'
  - '258 1'
  - '306 1'
  - '307 1'
  - '308 1'
  - '309 1'
  - '264 1'
  
# Minimum amount of players required to be online
minimum-players: 3

# Cooldown time - minutes before RandomGift can be used again
cooldown-time: 5

# Version checker - checks for an update on startup and displays a message if there is a more recent version available
# As part of the update check, the current plugin version will be sent back to the author for statistic purposes 
version-check: true